/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M20
 * Generated at: 2017-05-09 13:50:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/Users/leo/Documents/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cloudstreetmarket-webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492768743000L));
    _jspx_dependants.put("jar:file:/Users/leo/Documents/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cloudstreetmarket-webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t<!-- start: Meta -->\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<title>Spring MVC: CloudST Market</title> \n");
      out.write("\t<meta name=\"description\" content=\"Spring MVC CookBook: Cloud Street Market\"/>\n");
      out.write("\t<meta name=\"keywords\" content=\"spring mvc, cookbook, packt publishing, microservices, angular.js\" />\n");
      out.write("\t<meta name=\"author\" content=\"Your name\"/>\n");
      out.write("\t<!-- end: Meta -->\n");
      out.write("\t\n");
      out.write("\t<!-- start: Mobile Specific -->\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("\t<!-- end: Mobile Specific -->\n");
      out.write("\t\n");
      out.write("\t<!-- start: Facebook Open Graph -->\n");
      out.write("\t<meta property=\"og:title\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:description\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:type\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:url\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:image\" content=\"\"/>\n");
      out.write("\t<!-- end: Facebook Open Graph -->\n");
      out.write("\n");
      out.write("    <!-- start: CSS -->\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Droid+Sans:400,700\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Droid+Serif\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Boogaloo\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Economica:700,400italic\">\n");
      out.write("\t<!-- end: CSS -->\n");
      out.write("\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<!--start: Wrapper -->\n");
      out.write("\t<div id=\"wrapper\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t<!--start: Header -->\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!--start: Row -->\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<!--start: Logo -->\n");
      out.write("\t\t\t\t<div class=\"logo span4\">\n");
      out.write("\t\t\t\t  CLOUD<span class=\"sub\">ST</span><span>Market</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--end: Logo -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--start: Social Links -->\n");
      out.write("\t\t\t\t\t<div class=\"span8\">\n");
      out.write("\t\t\t\t\t\t<div id=\"social-links\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-small-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-twitter\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-twitter-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-facebook\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-facebook-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-dribbble\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-dribbble-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-flickr\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-flickr-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--end: Social Links -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--end: Row -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<!--end: Header-->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!--start: Navigation-->\t\n");
      out.write("\t\t\t<div class=\"navbar navbar-inverse\">\n");
      out.write("    \t\t\t<div class=\"navbar-inner\">\n");
      out.write("        \t\t\t<div class=\"container\">\n");
      out.write("          \t\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("          \t\t\t\t</a>\n");
      out.write("          \t\t\t\t<div class=\"nav-collapse collapse\">\n");
      out.write("            \t\t\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t\t\t\t\t  <li class=\"active\"><a href=\"index\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"markets\">Prices and markets</a></li>\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"community\">Community</a></li>\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"sources\">Sources</a></li>\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"about\">About</a></li>\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"contact\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("          \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("      \t\t\t</div>\n");
      out.write("    \t\t</div>\n");
      out.write("\t\t\t<!--end: Navigation-->\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--end: Container-->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("    \t<div class=\"container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("      \t\t\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<!-- start Clients List -->\t\n");
      out.write("\t\t\t<div class=\"clients-carousel\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<ul class=\"slides clients\">\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/1.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/2.png\" alt=\"\"/></li>\t\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/3.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/4.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/5.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/6.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/7.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/8.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/9.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/10.png\" alt=\"\"/></li>\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end Clients List -->\n");
      out.write("\t\t     <!-- start: Row -->\n");
      out.write("      \t\t<div class=\"row\"></div>\n");
      out.write("\t\t\t<!-- end: Row -->\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- start: Row -->\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- start: Icon Boxes -->\n");
      out.write("\t\t\t\t<div class=\"icons-box-vert-container\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- start: Icon Box Start -->\n");
      out.write("\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"icons-box-vert\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ico-ok ico-color circle-color big\"></i>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"icons-box-vert-info\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Easy to use</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Icon Box-->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- start: Icon Box Start -->\n");
      out.write("\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"icons-box-vert\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ico-cup  ico-white circle-color-full big-color\"></i>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"icons-box-vert-info\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Best choice</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Icon Box -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- start: Icon Box Start -->\n");
      out.write("\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"icons-box-vert\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ico-ipad ico-color circle-color big\"></i>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"icons-box-vert-info\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Fully Responsive</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Icon Box -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- start: Icon Box Start -->\n");
      out.write("\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"icons-box-vert\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ico-thumbs-up  ico-white circle-color-full big-color\"></i>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"icons-box-vert-info\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Social Network</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Icon Box -->\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end: Icon Boxes -->\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end: Row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--end: Container-->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("    \t<div class=\"container\">\t\t\n");
      out.write("\n");
      out.write("      \t\t<!-- start: Footer Menu -->\n");
      out.write("\t\t\t\t<div id=\"footer-menu\" class=\"hidden-tablet hidden-phone\">\n");
      out.write("\t\t\t\t  <!-- start: Container -->\n");
      out.write("\t\t\t\t  <div class=\"container\">\n");
      out.write("\t\t\t\t    <!-- start: Row -->\n");
      out.write("\t\t\t\t    <div class=\"row\">\n");
      out.write("\t\t\t\t      <!-- start: Footer Menu Logo -->\n");
      out.write("\t\t\t\t      <div class=\"span1\">\n");
      out.write("\t\t\t\t      <div class=\"logoSmall\">CLOUD<span class=\"sub\">ST</span><span>M!</span>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t      <!-- end: Footer Menu Logo -->\n");
      out.write("\t\t\t\t      <!-- start: Footer Menu Links-->\n");
      out.write("\t\t\t\t      <div class=\"span10\" >\n");
      out.write("\t\t\t\t      <div id=\"footer-menu-links\">\n");
      out.write("\t\t\t\t      <ul id=\"footer-nav\" style=\"margin-left:35pt;\">\n");
      out.write("\t\t\t\t        <li><a href=\"index\">Home</a></li>\n");
      out.write("\t\t\t\t        <li><a href=\"markets\">Prices and markets</a></li>\n");
      out.write("\t\t\t\t      <li><a href=\"community\">Community</a></li>\n");
      out.write("\t\t\t\t        <li><a href=\"sources\">Sources</a></li>\n");
      out.write("\t\t\t\t        <li><a href=\"about\">About</a></li>\n");
      out.write("\t\t\t\t        <li><a href=\"contact\">Contact</a></li>\n");
      out.write("\t\t\t\t        </ul>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        <!-- end: Footer Menu Links-->\n");
      out.write("\t\t\t\t        <!-- start: Footer Menu Back To Top -->\n");
      out.write("\t\t\t\t        <div class=\"span1\">\n");
      out.write("\t\t\t\t        <div id=\"footer-menu-back-to-top\">\n");
      out.write("\t\t\t\t          <a href=\"#\"></a>\n");
      out.write("\t\t\t\t          </div>\n");
      out.write("\t\t\t\t       </div>\n");
      out.write("\t\t\t\t        <!-- end: Footer Menu Back To Top -->\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <!-- end: Row -->\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  <!-- end: Container  -->\t\n");
      out.write("\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t<!-- end: Footer Menu -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- start: Footer -->\n");
      out.write("\t\t\t<div id=\"footer\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!-- start: Container -->\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- start: Row -->\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- start: About -->\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<h3>About Us</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end: About -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- start: Leaderboard -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span3\">\n");
      out.write("\t\t\t\t\t\t\t  <h3>Leaderboard</h3>\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"flickr-widget\">\n");
      out.write("\t\t\t\t\t\t\t    <script type=\"text/javascript\" src=\"\"></script>\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end: Leaderboard -->\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- start: Follow Us -->\n");
      out.write("\t\t\t\t\t\t\t<h3>Follow Us!</h3>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-twitter\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-twitter-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-facebook\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-facebook-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-dribbble\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-dribbble-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-flickr\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-flickr-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t<!-- end: Follow Us -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- start: Newsletter -->\n");
      out.write("\t\t\t\t\t\t\t<form id=\"newsletter\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Newsletter</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Please leave us your email</p>\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"newsletter_input\">@:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"newsletter_input\"/>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"newsletter_submit\" value=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t<!-- end: Newsletter -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Row -->\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end: Container  -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end: Footer -->\n");
      out.write("\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end: Container  -->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- end: Wrapper  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- start: Copyright -->\n");
      out.write("\t<div id=\"copyright\">\n");
      out.write("\t\n");
      out.write("\t\t<!-- start: Container -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t&copy; 2013, creativeLabs. <a href=\"http://bootstrapmaster.com\" alt=\"Bootstrap Themes\">Bootstrap Themes</a> Designed by BootstrapMaster in Poland <img src=\"img/poland.png\" alt=\"Poland\" style=\"margin-top:-4px\">\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end: Container  -->\n");
      out.write("\t\t\n");
      out.write("\t</div>\t\n");
      out.write("\t<!-- end: Copyright -->\n");
      out.write("\n");
      out.write("<!-- start: Java Script -->\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("<script src=\"js/jquery-1.8.2.js\"></script>\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\n");
      out.write("<script src=\"js/flexslider.js\"></script>\n");
      out.write("<script src=\"js/carousel.js\"></script>\n");
      out.write("<script def src=\"js/custom.js\"></script>\n");
      out.write("<!-- end: Java Script -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
