/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M20
 * Generated at: 2017-05-09 12:32:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/Users/leo/Documents/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cloudstreetmarket-webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492768743000L));
    _jspx_dependants.put("jar:file:/Users/leo/Documents/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cloudstreetmarket-webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" ng-app=\"cloudStreetMarketApp\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t<!-- start: Meta -->\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<title>FreeME:BOOTSTRAP THEME by BootstrapMaster</title> \n");
      out.write("\t<meta name=\"description\" content=\"FreeME:Bootstrap Theme\"/>\n");
      out.write("\t<meta name=\"keywords\" content=\"Template, Theme, web, html5, css3\" />\n");
      out.write("\t<meta name=\"author\" content=\"\" />\n");
      out.write("\t<!-- end:Meta -->\n");
      out.write("\t\n");
      out.write("\t<!-- start: Mobile Specific -->\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("\t<!-- end: Mobile Specific -->\n");
      out.write("\t\n");
      out.write("\t<!-- start: Facebook Open Graph -->\n");
      out.write("\t<meta property=\"og:title\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:description\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:type\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:url\" content=\"\"/>\n");
      out.write("\t<meta property=\"og:image\" content=\"\"/>\n");
      out.write("\t<!-- end: Facebook Open Graph -->\n");
      out.write("\n");
      out.write("    <!-- start: CSS -->\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"css/FeedEk.css\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Droid+Sans:400,700\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Droid+Serif\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Boogaloo\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://fonts.googleapis.com/css?family=Economica:700,400italic\">\n");
      out.write("\t<!-- end: CSS -->\n");
      out.write("\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<!--start: Wrapper -->\n");
      out.write("\t<div id=\"wrapper\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<!--start: Header -->\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!--start: Row -->\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--start: Logo -->\n");
      out.write("\t\t\t\t\t<div class=\"logo span4\">\n");
      out.write("\t\t\t\t\t\t\tCLOUD<span class=\"sub\">ST</span><span>Market</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--end: Logo -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--start: Social Links -->\n");
      out.write("\t\t\t\t\t<div class=\"span8\">\n");
      out.write("\t\t\t\t\t\t<div id=\"social-links\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-small-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-twitter\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-twitter-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-facebook\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-facebook-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-dribbble\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-dribbble-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-small-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-front social-small-flickr\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-small-info-back social-small-flickr-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--end: Social Links -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--end: Row -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<!--end: Header-->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!--start: Navigation-->\t\n");
      out.write("\t\t\t<div class=\"navbar navbar-inverse\">\n");
      out.write("    \t\t\t<div class=\"navbar-inner\">\n");
      out.write("        \t\t\t<div class=\"container\">\n");
      out.write("          \t\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("            \t\t\t\t<span class=\"icon-bar\"></span>\n");
      out.write("          \t\t\t\t</a>\n");
      out.write("          \t\t\t\t<div class=\"nav-collapse collapse\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"markets\">Prices and markets</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"community\">Community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"sources\">Sources</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"about\">About</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"contact\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("          \t\t\t\t</div>\n");
      out.write("        \t\t\t</div>\n");
      out.write("      \t\t\t</div>\n");
      out.write("    \t\t</div>\n");
      out.write("\t\t\t<!--end: Navigation-->\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--end: Container-->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("    \t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- start: Row -->\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"span12\">\n");
      out.write("\t\t\t\t\t<div class=\"hero-unit hidden-phone\">\n");
      out.write("\t\t\t\t\t\t<p>Welcome to CloudStreet Market, the educational platform.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"span5\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t<div id=\"landingGraphContainerAndTools\">\n");
      out.write("\t\t\t\t\t\t\t<div id='landingGraphContainer' ng-controller=\"homeFinancialGraphController\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control centeredElementBox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyMarketActivity.marketId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyMarketActivity.marketShortName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t<div id='tableMarketPrices'>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar dailyMarketsActivity = [];\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar market;\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"table table-hover table-condensed table-bordered table-striped\" data-ng-controller='homeFinancialTableController'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Index</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Value</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Change</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr data-ng-repeat=\"value in financialMarkets\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>{{value.marketShortName}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align:right\">{{value.latestValue}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class='{{value.style}}' style=\"text-align:right\"><strong>{{value.latestChange}}%</strong></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"span7\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"divRss3\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"feedEkList\" data-ng-controller='homeCommunityActivityController'>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t  <script>\n");
      out.write("\t\t\t\t\t\t\t\t\tvar userActivities = [];\n");
      out.write("\t\t\t\t\t\t\t\t\tvar userActivity;\n");
      out.write("\t\t\t\t\t\t\t  </script>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t      ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t      \n");
      out.write("\t\t\t\t\t\t\t  <li data-ng-repeat=\"value in communityActivities\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"itemTitle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listUserIco {{value.defaultProfileImage}}\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img ng-if=\"value.urlProfilePicture\" src='{{value.urlProfilePicture}}'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"ico-white {{value.iconDirection}} listActionIco\"></span>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">{{value.userName}}</a> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t{{value.userActionPresentTense}} {{value.amount}} \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">{{value.valueShortId}}</a> at {{value.price}}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"itemDate\">{{value.date}}</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t  </li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end: Row -->\n");
      out.write("      \t\t\n");
      out.write("\t\t\t<hr class=\"hidden-phone\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<!-- start Clients List -->\t\n");
      out.write("\t\t\t<div class=\"clients-carousel hidden-phone\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<ul class=\"slides clients\">\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/1.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/2.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/3.png\" alt=\"\"/></li>\t\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/4.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/5.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/logos/6.png\" alt=\"\"/></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end Clients List -->\n");
      out.write("\t\t\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--end: Container-->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<!--start: Container -->\n");
      out.write("    \t<div class=\"container\">\t\t\n");
      out.write("\n");
      out.write("      \t\t<!-- start: Footer Menu -->\n");
      out.write("\t\t\t<div id=\"footer-menu\" class=\"hidden-tablet hidden-phone\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- start: Container -->\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- start: Row -->\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- start: Footer Menu Logo -->\n");
      out.write("\t\t\t\t\t\t<div class=\"span1\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logoSmall\">\n");
      out.write("\t\t\t\t\t\t\t\tCLOUD<span class=\"sub\">ST</span><span>M!</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- end: Footer Menu Logo -->\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!-- start: Footer Menu Links-->\n");
      out.write("\t\t\t\t\t\t<div class=\"span10\">\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"footer-menu-links\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul id=\"footer-nav\" style=\"margin-left:35pt;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"index\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"markets\">Prices and markets</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"community\">Community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"sources\">Sources</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"about\">About</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end: Footer Menu Links-->\n");
      out.write("\t\t\t\t\t\t<!-- start: Footer Menu Back To Top -->\n");
      out.write("\t\t\t\t\t\t<div class=\"span1\">\n");
      out.write("\t\t\t\t\t\t\t<div id=\"footer-menu-back-to-top\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end: Footer Menu Back To Top -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Row -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end: Container  -->\t\n");
      out.write("\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<!-- end: Footer Menu -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- start: Footer -->\n");
      out.write("\t\t\t<div id=\"footer\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!-- start: Container -->\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- start: Row -->\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- start: About -->\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<h3>About Us</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end: About -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- start: Leaderboard -->\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\">\n");
      out.write("\t\t\t\t\t\t<h3>Leaderboard</h3>\n");
      out.write("\t\t\t\t\t\t<div class=\"flickr-widget\">\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\" src=\"\"></script>\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end: Leaderboard -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- start: Follow Us -->\n");
      out.write("\t\t\t\t\t\t\t<h3>Follow Us!</h3>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-grid\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-twitter\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-twitter-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://twitter.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-facebook\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-facebook-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://facebook.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-dribbble\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-dribbble-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://dribbble.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"social-item\">\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-front social-flickr\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"social-info-back social-flickr-hover\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"http://flickr.com\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t<!-- end: Follow Us -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- start: Newsletter -->\n");
      out.write("\t\t\t\t\t\t\t<form id=\"newsletter\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Newsletter</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Please leave us your email</p>\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"newsletter_input\">@:</label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"newsletter_input\"/>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"newsletter_submit\" value=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t<!-- end: Newsletter -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end: Row -->\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end: Container  -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end: Footer -->\n");
      out.write("\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end: Container  -->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- end: Wrapper  -->\n");
      out.write("\n");
      out.write("\t<!-- start: Copyright -->\n");
      out.write("\t<div id=\"copyright\">\n");
      out.write("\t\t<!-- start: Container -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t<p><a href=\"http://bootstrapmaster.com\" alt=\"Bootstrap Themes\">Bootstrap Themes</a> by BootstrapMaster, thanks</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end: Container  -->\n");
      out.write("\t</div>\t\n");
      out.write("\t<!-- end: Copyright -->\n");
      out.write("\t\n");
      out.write("\t<!-- start: Javascript -->\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("\t<script src=\"js/jquery-1.8.2.js\"></script>\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\n");
      out.write("\t<script src=\"js/flexslider.js\"></script>\n");
      out.write("\t<script src=\"js/carousel.js\"></script>\n");
      out.write("\t<script def src=\"js/custom.js\"></script>\n");
      out.write("\t<script src=\"js/FeedEk.js\"></script>\n");
      out.write("\t<script src=\"js/raphael.js\"></script>\n");
      out.write("\t<script src=\"js/morris.min.js\"></script>\n");
      out.write("\t<script src=\"js/angular.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t\tvar financial_data = [];\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\tvar cloudStreetMarketApp = angular.module('cloudStreetMarketApp', []);\n");
      out.write("\t\tvar tmpYmax = ");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write(";\n");
      out.write("\t\tvar tmpYmin = ");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write(";\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"js/home_financial_graph.js\"></script>\n");
      out.write("\t<script src=\"js/home_financial_table.js\"></script>\n");
      out.write("\t<script src=\"js/home_community_activity.js\"></script>\n");
      out.write("\t<!-- end: Javascript -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(191,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("market");
      // /WEB-INF/jsp/index.jsp(191,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/index.jsp(191,9) '${dailyMarketsActivity}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dailyMarketsActivity}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<script>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tmarket = {};\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tmarket.marketShortName = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${market.marketShortName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tmarket.latestValue = (");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${market.latestValue}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(").toFixed(2);\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tmarket.latestChange = (");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${market.latestChange}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("*100).toFixed(2);\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tdailyMarketsActivity.push(market);\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</script>\n");
            out.write("\t\t\t\t\t\t\t\t \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/index.jsp(233,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("activity");
      // /WEB-INF/jsp/index.jsp(233,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/index.jsp(233,12) '${recentUserActivity}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recentUserActivity}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t  <script>\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity = {};\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.userAction = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.userAction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.urlProfilePicture = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.urlProfilePicture}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.userName = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.urlProfilePicture = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.urlProfilePicture}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.date = '");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.userActionPresentTense = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.userAction.presentTense}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.amount = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(";\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.valueShortId = '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.valueShortId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivity.price = (");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(").toFixed(2);\n");
            out.write("\t\t\t\t\t\t\t\t\t\tuserActivities.push(userActivity);\n");
            out.write("\t\t\t\t\t\t\t\t  </script>\n");
            out.write("\t\t\t\t\t\t      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/index.jsp(240,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/index.jsp(240,31) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("dd/MM/yyyy hh:mm aaa");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/jsp/index.jsp(488,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("dailySnapshot");
      // /WEB-INF/jsp/index.jsp(488,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/index.jsp(488,2) '${dailyMarketActivity.values}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dailyMarketActivity.values}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\tfinancial_data.push({\"period\": '");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("', \"index\": ");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("});\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/jsp/index.jsp(489,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailySnapshot.key}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/jsp/index.jsp(489,84) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailySnapshot.value}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/jsp/index.jsp(495,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyMarketActivity.maxValue}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/jsp/index.jsp(496,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyMarketActivity.minValue}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }
}
